
-- Custom SQL migration file, put your code below! --
-- Generated by scripts/cloud/migrate-cloudinary-images-to-r2.ts
-- Source DB rows: cloudinary-backed images from the provided sqlite mirror
-- Target bucket stage is controlled independently at runtime
-- Final DB env in this SQL patch: production
PRAGMA foreign_keys=OFF;

BEGIN TRANSACTION;

UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'E66x70_QAcGn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VtD8QSf0eQOF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h-fhpzh8pL3n';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EXCTbF2IzNy4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SS62k3nUvSZx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RYkxD7cqPdey';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'purjkSmPjlwq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OOnggJDho9eu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IAmS7jFhNyZO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'skAvU43WpsFL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MR66HAZPh_3u';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MNZX-GT5fSc7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pqS-gpEr5B6i';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6uICchf8CXB5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'va-dug-svxxf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'usOPtJqsshpw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CVaNOi2D01Wd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ta1to9PJEy3d';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4sHMZHB_W8XQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IeRMk6LKKh_G';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TC7z-4zB2PBg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NmsHzoRQ6JYp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eB8tgmE-ehgz';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KrEyBC0ikQ3B';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CLLERBWYThY7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EWqHnbsTERWJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'j9tzCQpkamwA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CNejQDDDKWA5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IdI93Olxxrl3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YeaHK4-t68bO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 's2_DzAerF_Sx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oy0zoymmROqY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HbMNeXMA3EPH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2PxzsXoOWUWs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gTXTVTslt40i';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aZdsGWfGNT1j';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1sZOG2DgnBUe';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yIPLQR5as6Xp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hPtVf-cgydkl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ZHMXimOia_Y8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'm8gBUYUx4pxw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'c28KHBmqQ8Zm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'te6JN_29vf_Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VaCf_dX92O43';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4nw1ko3N3S-I';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iBMX4fYuUW_L';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WtZ_bSBXRTom';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Fub_tsVURx63';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GOdVMQaPg5ml';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4yJxK6e4Skyj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cfo711o4b0Yy';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1dAX099JsvHA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8mYUZgGDZA8s';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'e3CMcZ6TaFQB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gwWi6gKT3kYE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QRVmOXFWKWQd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Co2Ea9cuf2ZQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kqZ2nfqeHKFi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'W771j_9uRUw9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XvIAGtYzQLLa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IXlGv-pWI0KP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7N27zJ8tHtxv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4Tj11676ck9f';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'thdukobaKv38';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Rt-Vdd4amX0x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6yf5wtwQqUzq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lOn0OsVlcdzP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xUICjwVi-9TZ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7DHtINjfuUlj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ev-RIGwKIgWK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ED5-EqFtQu7o';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YqBNCfgivXDq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IXe53qKYoX5q';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Fp7YI-Mj3gZ0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8EQqVUnBy2zs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ihrzHuwWJPxa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OUp-3ohvQPvY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 's7h1k908unFz';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4gQrogIKNgAk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cCDa0PsNwSw2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nYy3ZIBG4yPE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hma4fdYh3URV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'mdJ5zfHIVAaA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HOa06I2ggWXH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WgqGO0Pbtc89';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tydyWsnSKusH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AXFtAVi_9Obm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '78ZVK5URBWHn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_fX6-W4GQcAX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rphpDDNNmrrP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JFYB9VAcIWso';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'twe7XST2wGzl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eJxvB-gijPje';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3alO3ekIGJkU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XRui9nKlitSu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jxTfRvoDShre';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8WryYIL6H0Px';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IGP5p6XdMe8A';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eKcy2hNt6_iy';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'P0LfnoKi-Hr0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OKaIEQCJVaO6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4u7H6wKQsmgJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PROCWYkQkqzg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'T29cTnTGIv4D';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'M6XZxBtBa_y0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'K1VquWTtLdFf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IcxGcqD527Ao';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'i9xx1VQEeKAT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6ITJwYnH1sgH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HK498smxhKbE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4dttA0QgOmis';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qmakPd34a_S6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EV2KSz-mTNPO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IWeVJNi_8GAU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4HHuy3e-D085';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wsCNUDG-Z7O7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'uNV2SMXKXp-k';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ojRv5NZ2qdUk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3yAIy4Z_MWtv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pAUAiw6M4thR';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cT6TUQMFI6cr';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'v0I-3tw38_XU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aDxpEUoe_D-p';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hptbqQ3lebCg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sM3YpGrMcD-P';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'uHuaDp2QYRp3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'avr2uiwEY8P7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ut0QJxlSBlmw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MTA_U-zyWz9A';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qHEFbFWQsm9w';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'j6y1ZjJSfpT0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9HAiDxaG7YRu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jPVqdX61MRay';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kO3flYEer-r3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zV4xjJzBZj_L';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0TvicScatwLC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oBYxqjrSHGaU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Cp1RuqwGCLQo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WB8uvCMwgCxM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rhyHVP59cvjv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xLzCxd8YZPdO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QEcKzzv4zyA9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'S2yseCJh28b8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cg4iIJNU7VPE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RuZUTrmZH_uo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '24tznFZNYqB-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MBw-6koO4dGi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1U8eLI8zgUxY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8Fwro3WC9KdS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jc2COzCJUS4h';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'N5lzhQBlGMNa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EMiM8G_tKEYf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MNmjEy9SBluI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OzJLlIpMRxl4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CRm2rqCqNors';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'duN2wmivzhvx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GYSc-Tg15ly0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Cfhd711tY8Y1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8XuoQaOFWULa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AnMtOJ9Rt08C';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'o_G2FWFTqEun';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cZHm_qS8HoHO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1IbCZ44NAb5H';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ffS3hAqIf3ru';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1jXpL8wlAiID';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ehiCh4_yE2sU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4RfVp0vlBvyb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ksVjAk_FUoZP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WcSIbAHz6kv5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ly5e0yhTrkrY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_3noOQ6aGk9w';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aS7YSuR6HDkQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fu7zisafDNOM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IGWETWHJsQtu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Pi3-U_2-d4WC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '24WtGWelxzeF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YbeCZ8jmX4Ke';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fpROQDYApRmo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YpgbeWP2eNgj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'If9c2VLiRUJN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AN_VrVheCE4O';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'r5Bm2umBa_w_';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_jiWeUsPr4R-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'b_NHuowdoHQk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'DWimVdpLIGrM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TSNQg1NA3-vR';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jUBg-RsiHXK8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'g-N2hpqwtxhk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dqADI01RvFay';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ZbtYUG1CF_Gb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Xz0PsY68_4EQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tq58vTV7HbvI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xf0W5XWlw2v4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yFFlIV2braRS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RR9JrEZFBgsG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ggqrAasdCfJJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'e3P2LebfN_55';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'J6m_mY3IxctU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xXb7tTqRp21n';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8aX9UP44E1Re';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oK6yng7TjixQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'W_2kKht_8j6p';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yv_H4tvoc9o4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PBp8J3MuxxzR';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xDakGLeMJFpv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ED3HISJKqadb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '51B1vWwUuqb8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'U5AFenMVqEYG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'L_B22AxIkYs-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yrRU1ypjjl_E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '82OOLIVvzFkV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SgkIMEZnHT8c';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PAAyQrX-K4lS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dCehhyPXzoTo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bY8ehvOVP3UM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IdSsDWtxAvYG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '04I-yUQhyJd3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NnbjjsvRxnae';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4mVIT34uojKL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Dqijb94FRgV1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9-ng4GkHRH_D';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'uYCZkg7VGok0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xUFpPLdsvVkN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lgZpeScGdEze';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'US4ujW0pFHfH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8MWYM15-FeN1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MpBHRKo6d02v';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'E89TgUssauT-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'r-abxc7YlwIj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'I81-oMAaxlOE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0O5BVmAaBYUh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '016jH1hicLUM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bHK-QU70ij5D';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '38xmcOCgfRlL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TyGgBiB_1y2N';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JBbZT0nDCZPk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0iRFlvb1epLb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QF_NvezMjIb8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EsVFT4xXEE6q';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'C3KPF__uyUT2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'drbMEQTaugQx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cMfwLweD9__r';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Blo2i62cgO5w';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'maWHDORKw60m';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XOwTcL6xinRM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_yEHj5Cuq-fI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HTGDuJ7IO047';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bzmUdgCvUVPk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yzlHypyxVkdx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7FvgB08Twioo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4zl6WpqU3cGj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'STVXyH7UJiaI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CXNHxKCWz4Cn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'J0mkBmhoCJIB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Sgq0GymXdx2G';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QrAGrzWl0IK8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2O1iFvIUC24p';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JqnJeqHAC4R4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-PDphWNTsQC6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2gjePctC9x9j';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aCPSl8abrK0Q';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Hag8gFVyFync';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NLcQhRaYrTmR';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'A_m3kngYAas4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gYHRI043PUbX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ea24OoTJXrNi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cOuQsW6j_SBW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gGEMpKYEHLOx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nsZa-_TSUCGg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'm4qW8m7ZU0vE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'P5KWmuZSgor3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CjaXtU3eHXdY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nsHxNbQZuuAG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SabTyOQ8OkXW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HQoPFamHFurp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CoS7Pj9jS71-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MMPr52Jvf8jX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QVNiBvXV3KqJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CUlxuj8HSyfX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oeGC-9JFk7pL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'av5vJfsvvB0r';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NoArPasXRpld';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2pkrwnYF4oA5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9f7XRNr04ya4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XnhEZ6AmqrWu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sGCn9iIDB4FZ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TTvxaKMoMJoC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ex83IzdWckms';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'joY5VyTKl8BF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gURJlpdMoqO1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_t5ktXvRLpx6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4BN5zvoKF5Wy';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aC8tmL2kqIAA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'g7cp6Raszlqk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IXABBC0czlcl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dkXPVlVLVSXP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3aa_CuxHGFqM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zVONXSqc_iJt';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HovbrHyRXsw8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6KdpAiMwzsuv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3o6irqIfrOkm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IXremzUpyRmQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hMDnLVDXINwg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HmG1dM0Whire';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LMzJVjczrbYX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8R7nvzvQQZfv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'z0DvxUInMsRZ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7VaYxxDtqycv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RBfiLVhu9xtQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7rzmUd2TdYBV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'FEQPwVb2zVz_';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jV0iRvzhHrz6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'DV-jDb2MYwjr';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'U4jbto4DmJ4H';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HCB-Zh7fRT2Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ynroo3BEBWeM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HW4MiETXPg6g';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bn8wNhOFXrE_';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NtjfRsQDcb3K';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EuG64aSysVs5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RFvTcXqvNKhu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-8dyXiQ_Q1rU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UFXtAbMDJ1H3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KBf_ZVhJPsYV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ad8a35X-Jh0E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'APDqgIXSlUA1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'x40KBDAiZG-f';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7Het0Li5iDsn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Sp5hOZxTwdib';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TD2D1Qj9FK_r';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RmhtEDMyBDpc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'DvoKKDE44dqn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4nI7PQbT3whl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JZrpKAekvMUb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'i9dc1vCgsceY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EQ9kucrLlG9d';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oCnjTFUrJXuT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dVsd4-ybrdIE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zqdCIEHPMboD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jnuspm39ST54';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ItiLwEak5rDp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_1wUdzFfZTyx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LqDABNJqJKgo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'W90Q3inE40FT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LgzhN56Rh7gt';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UChxomVhmpIZ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'q8NxrJp99amB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ly1oMZa37W8N';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Q54waOwxj3qj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Mypa3yvTMNEF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iMwJgok7b_8Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KjDNXHUgx8ih';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gUoNE1fUKE8t';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VwfDGQ0huS58';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9AeaL3bSJV-9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CgTyggglKNrY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YB-hL7Sn2vpo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aqfXnQ5nMoIh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HYuzy5WlGBhe';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1dvw8pRzsksa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Dihg0Oa9eblT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wFfOOxmrflwo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '5XFLH7qRBfsv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oH2pQD7oh67w';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9JN5amHi1YZd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TjMncjOycubw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iP5Squkz67Uv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KT0AP_894jK4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 't3c9MINoPD3D';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zTyrrP1X0Pti';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GIJ_JdFtgGcA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fZtWKS05l77l';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-V4wVw_w7N0v';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '19SJkPwQg3X8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'D3A_i67Uya3m';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wTMCoNit7aLv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SbpWDrCB6SN2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cKuNX9VPqs6x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gVcPFNszyHpr';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SQBzih4kgUVT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KIt1EzamojsT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '11DWs7V1GtJb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pdTj32aDbxBY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0N27f841A0Xs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EbMnOkLK-8If';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1FpMK6akwqjC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Rg0gW2pkAhtW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9AISM5v499oX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nabcaSxTc5zu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NWPQmp2BqOTm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'L8hK5pEnFA_x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dNeqpGODZA0s';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OlcL5UdOd3_N';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hTcpJz2lANbg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SxfjjQepUzPY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IoJNfp_t2Vg-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wr8v5TpDevOY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1GI6rNSHsxlW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iGWQyhEBQl0j';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zCNCabYFDKk9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sflo2bYhQ8jF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'we6WShMD8vmb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SOrdd7B3x1tl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3DHevwFJVHC6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'umsnjvRoi-mX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xQLIxNjXBhlU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cj-7gmjUUZXc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '99hZ5YZg1kyK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'htkwb1ctYjLU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iJ1XL6j15de1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HVTg20bAJV2T';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '5OJfH_Oa2SOY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'o9ftxI76XynK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'e_TOxMWOLFqV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iqJIzesKBpYs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ic4ZvCCNF5ug';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2gGbrgpWSp-K';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LXtNqnh4aFD6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QQ-46fHJ3JvA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6sctIzb1D9Qx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '__EgxA03-3tg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WBiVpDyQV3nU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dQmTnYU2Zd0s';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_caWu1ruHQdu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'BXyuTEfrRyQ0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'K-mpAj4CJS5V';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jZO0c9UdZJ3W';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dlxnpbuPD2vp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0pa2co71scuB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'B_0gFSlasl-5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ScdhHZwG2UeG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IkU-YL-N1Hh1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ofloUZcTtn-X';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'a2Cbv2lEVRlR';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VRVKrQlCwbpY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9qMN_OXaMUU1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yPSEYjXDuE7e';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eWa1apyrVIgS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ohsJmXtNBIf2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QORqiEmYXbX7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'frEGPGYcAI2T';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JpwenHBMig2F';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4av9IFalqM-x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ZV1hfq7esi4E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4vNXKuHDHfSg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ozJY3YG2527z';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wyMU8daGtjXq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tOKxDO1UudjK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0eoR6lTVWDUJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Z9wu9BqB2zDa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sTYmtRiLZiwa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RtishId0BWG9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IdU3FKxrV5in';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VWSPz7RzOUcO';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iEytIxe6l4mi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Xp1Ol46kOtS5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lqudGsUXZmOM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SOfhVPaL84ez';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'L8J5stXdJH8m';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'V76oyxkVJwYE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CFoPfRKIpBJq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XL-OFxC4KqLw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iLFSbuReLpeJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JddgaYMxgHUq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'soBbrrsDto15';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'p17R4LcPUULA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'vSrtyJBwu3QL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'M7jVJved5_Dc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'D6DDSZp8tbzU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_Istd9c_MDdo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cec771_zP06P';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AggVqCFIGpKd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Pb-RlPAZI2aV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'm84FBZBSLP0E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hq8lZ8mNl9Bm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wfoxfhs7bctc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LPw2T3zPbOmM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OGuVAekzMKKL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'A2sU2z_xtxVl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NuX13tFoXX8P';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'mGodBpBO-h5J';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QJA9hgXB_B-y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TOU3t-O9ut3p';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oTbH7i-G2aE5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dQuihc8VF5CD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_JRxXFNSUoVl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'E1IKq4UCK4Pk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TjCpBC_cv-DY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dJ-vyPQStsFF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4V1F3rcNmcu8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wq2WUoV00O7q';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jdj0uzVUkmPh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IDqdKUx0Yx4G';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'IyiGk4pO20Lj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LeHg4ZJcZblD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UNergYU4kKwH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'b2HVoZAFbDtb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h3bSNMjCBZjM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sU6-m-op13X4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HHA-0GIgs9Hu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jm1fi_usJhNI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'moFO4msBufv4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-PTQ9BHcyUr9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xNvvBv7j3ZNJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'mQR43d-1LO3O';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'v4rBb6sE_8DI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ouEoIPvlFTjC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6BbeOZhPzTTa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h1peYOHcuXKe';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nqm4eMZ6-h9E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yWMSWZfx83la';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EjJD7_EB5MRk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fwt-Aq2Y-fFc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'v2Tlu_K45TYw';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'A8qHn5QZ5RgQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lnZEevqHrIeB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'q72Uz1Zj540w';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3cPhLqeH9jcT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'X2vMPfVbAKRh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Vzz8dX55bAtt';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qAPXnlaPnsNH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4hHDwOyAtgBQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'I0XEiX1-TMAU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ZW5YSVZM0Jdg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'abohbPnGvaY8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4u1S50CIdzfS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qwhGpIJSWFTm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jSYXXef8e70c';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-lKh9zJSrKGm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UueI9dWhKLdA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'p6-DE84I-Fvi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'i6wYK56RGXr_';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wFFHcau1E7x1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EwYOJfU5-381';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kBSMkumAMJK9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yTK_eVGN-fO7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OEap9Sir1aok';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LEE1ex3eq3LJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Scvtht5FhjYm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gZe15-NNJHue';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dQqhSV2Pigzq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tg9IxWvvVeot';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GP2QIahY5zkm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XTP3kaFfU3oA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sBPqEAQXPjST';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lfmR2puWZn8l';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9NtLL5mV1BHz';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MQvETTGRskLa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ErbP82x4owNL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jzxRUF48hf6n';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nWsyWZR8v_0U';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OTEksw4k7m_6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'p8kMK9v0a_Vc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '88_GfedYxQW8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'vuS2gPl0AOEC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xITzWJqg7JI6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '5D60NcE5qOY4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aDLXBWLesqxC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'epRMLwWdFbXf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'm7sTmeNnv2yv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Pw8R7BQGmP6h';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AbmuDxZC4vXK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aw9zI9ogAcc9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XiQfwi2w6Qp6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ioCWyAmZPgJ2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1hBeQgT71TJ-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OtM_kVR61yfH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Pdiyovwsyk0g';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qg5Pxe3gLNVQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'x5hdFGCH2ys3';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rN9_1qmQbGSl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ONi8Y-t_j3gC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2xZYTI6NpVIK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yU1KmyKT1EPn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '84kyb2SdkIdK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YLjaS1IoUsUs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_G9CWmCN_aw6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'J-ZOFrVfjb8y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8P8POGll2lsh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2zi02EX1-Bjh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kfgKcoOBTACG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HYsMAtMwOZkC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dcO-qygz-2Px';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rm1DHrRJgi-M';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9EtsFgmdZ4BW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4UpQMCS72nmo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'u5fSsMTxQ0hn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qxp61PMNnz1x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GA9LC9u8SzAU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'RkhbhavILACV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VZZTJckKiwIq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0gTfSE48Y4jk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QarBwdYgKyeh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'f7d9A6nY5-tx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sqjV3yyzS6xj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3-eSAxegCPSH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4-rFYHRF_aOY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rFEaerqsDoB2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PGLyQI0HLUQl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'mGb73mQqxAwX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gFvuRb3lPVDE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NlhXAKKIP6lv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'y2hXEcyvdljT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XC9V_6d8do0a';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'f1D6EYjQiNos';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VObYIKltH4k4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JGPjocV8B40p';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'f2LsaBF07P5V';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LvWxSk9Ll56Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Igw9ICf2L4sK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jjNU4DsfIWO5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wat68_pHvaPd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MlD8cU5ayifM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iOA0pB39176D';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ved-m7n__E9u';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '08tl9FYp8qO4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '5bK8X9TXa37_';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0giCXCw1EiBG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '43o3ut4SrFDh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'rewLd5uhg0ma';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'L5CLNw7f2MeV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3SNuuan1sMhM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'I3rPqwYOk0iY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QGQkA_gwu_uY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2ijwQeuL0ON9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Ud8hHYQv8iYu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YyLGG5tTdht9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ysHc9ww6IzDg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '38zEz2edbbvI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ELVB2RUoF8Yf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CGldtEQ5W6m7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8RxFaE7VYyEE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'z8-sn9TO_MFF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qgcQAs3Czt5u';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'HUlLBg6uDg-U';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jaeE6wnK4FkQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'mAjrjAC473Cc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'xiXVYWNm3s5x';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GH1MFHJOqjbU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3qXK5QLtLPaD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4SjaGHF7gk4d';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tq9HuWgazhHc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YZ1c6kSIo7tb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wTWNIzIrbGsA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'XJKd1qPS1-5n';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'I5wWxts48Hyp';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'SHYQKRfspky2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'uhcsUdexoxUE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iSnrWG0wKkyY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ygIM-nnMleqS';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'boqZ1cHPXgvP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PMayviTMNn-5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tW4xURrxiIe2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'n7l9x1DROSSZ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qwxhKP21sB20';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AvHMds5qNhf8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'b6_rgOk1-sYI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'o-BG5Dvw4Wp0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OMSrcqFt519Z';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ADgl3dIKR56j';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pgseRx3I-tFG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lEas4fAvHQ2g';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ogWlPTApHHAY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2sEOdm_cXTru';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EpP_iT2THb2m';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'qblrjs7VudFD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VHpeLPCoc41o';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8GFkWp7sVTBT';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'DcNHkYCMPo8P';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GiXMAbOmdTc6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eMcjnT9spmlf';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aKNexCk4b64s';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'X9aimH6nmBtA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'dY8SRmj_WT2o';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'PHOMeh55VKV5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9z3MuIp9I8zu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ge7ZtHmXtrqK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'H3X-LEt_MmkP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Xyu_M_KCGU1Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'G4Z0gccD6mYs';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kh6SDfVc750J';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'iR7NXcaq0-05';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nffHRzzdLY9h';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'epfydig05fho';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QcXNXhw-_S3A';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'vWWpOR0YlJu6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UPYkFCg0vuZM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gCAaxbXH6ZPB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'owi3oXOof7nh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gNNUU9UDaB7a';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OuQljzfqvIdj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '_DR9QqrTkC3J';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1V6xTm3sB-Te';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cnR7FGShxegN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fUp98IZOn4rB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 't-zKxjt8YD9E';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'nKtKwCHmETyH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '3dSM8EfUl1WU';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'veOeAGpPRp3i';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YFDJbS6jLqN0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Q2tWmxzVK5tX';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UGS4hEbycJRv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JxKDKUzNUUtH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'F4OsgehSnA5W';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7ObZrb5Qb4Mg';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4HMz9m7W6-eu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'J5d6qsB5vbdd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4K8W0TwuKxPI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2bxd8ihYfYOo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gZgquthwfQzn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8zLez-SEI48r';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '26x5TxnBP2DI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Zk1nYBVJ0TDh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eUaFDDV2OI_Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fnHOalgD2HEc';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'GspTgxkM1Swz';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jORVKXMcgjC7';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'c6dZAC6Jin3Y';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Rbu-srMAlZ9O';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '14EsEb_z2LDK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zIop3BvJZ1Yl';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MDIMMniU1fr6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'yffeaAgqkF9a';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YowiO8y037iE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '1IudA6ETtPOz';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'G41_krRRdeld';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'WwofCWS2cS6X';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hVkqNtmFSjz0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h5hEBmgWapI1';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'khJzBS89ZAAF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'JM818avCpymD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '6IcXhQD2XIUA';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h6QEqKt46pdV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'eIXnH0mc2mCj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'tceU9T0FWnPt';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pEYqgp4ki5xh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'aphOcNcvxZLm';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '0I-ySlzWm0ab';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'QRzpwlAhhzjv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'b8rb5aQay_HN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zYlCWOXrihme';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'cdGFr3kuaSRx';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8v9HkmPQqZEd';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Gljz8SFch_-4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'V77cIeDhgIUG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'M3kL6H_LDNzq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bfsKFq6OJCdn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'K_qVHLl-IoN8';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'jeOPiejlgxRW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '2w6LsYJWNLt-';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NkebBjViq0Ho';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UsX_DnEsHg7z';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'l_O0gRI4Ep5i';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'J8xjKMNFeuzI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'u4PXtrqEbNvr';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '7H33tavm_y0u';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'zhwWZ9NxrcQn';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MXIaaYuSnN0R';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'uw1As6lvZyKC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kU9-DNiFupBY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ockIZvZ3rfCq';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ZjqfmSYoGC2W';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '10s8L_cNzi8F';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '5uy-G0TYGEH9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'AKX_oMlVrHRI';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YxkuziEZvRMo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'N2Dbicytw3JB';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'W2LXg3QVsRzH';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gOSRYr-p9G-4';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Z1p5qmCj1KsL';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'S_FNqj4FMi61';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '9Hc7VBdO8dzy';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'TUKxZfucrde5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Q9B_KP5LfkhD';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'wLfvXZXzUkI5';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'e2fWcroLdmwh';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'NKY58j-UbrpM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'UdeBhJwMLinW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'oEguveQZViBQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'czeAgc0dSSzk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'daFDVv--KwNo';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'MQGNaS6FbtlG';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'lnqBtaGG2pxC';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'h52S9IyAk2qj';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ycQLHj1F5JxJ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kZ_rDZvoxrQb';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YBG-LrCbQdYk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'YvEGNjPJ-f0O';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Hzq53fAsz2jP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fSK4KYmIcthN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'LScFWZL9WbSv';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'bFEggLG3faVQ';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'gLtZbnaucWHY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'OPs-NIUaUO62';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sNoDa0DobXQM';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '4LL2V00Nl_H9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Y5GlsmiaHFjY';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'hMjky0EwItDk';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KnH3KxqYUUIV';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'duj-OM4ifNdE';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VuvxJ08bG-Gr';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Yjdpjy59PEmu';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'VbJNox1cflQ9';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '92AzggmnuI86';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'G15vFZAPbMlN';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Z1ibISz-RdzP';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'Znagp40SA3F6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '8m6HsscxFNZK';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'sIh5GgBjhxW2';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'fyIU49sso3pt';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'kVnblUsRt3sW';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'S6Cn8gvV91O6';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'ycsr2PsULEl0';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'pSVh7o_lZ-Fi';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'CoVguSOsv4Fa';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = '-EsQ42Bi6B00';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'EfnPsGp7qsaF';
UPDATE image
SET cdn = 'cloudflareR2',
    env = 'production',
    cdnId = NULL
WHERE id = 'KB4Y53OkRfCT';

COMMIT;

PRAGMA foreign_keys=ON;
