<script lang="ts">
// TYPES
type Props = {
  isGenAI: boolean;
  locale: string;
  absolute?: boolean;
};

const { isGenAI, locale, absolute = false }: Props = $props();

function getTooltipText(text: string) {
  if (text === '✨') return 'Generated by AI';
  if (locale !== 'core')
    return {
      en: 'English',
      'zh-hant': 'Trad. Chinese',
      'zh-hans': 'Simp. Chinese'
    }[locale];
}
</script>

{#snippet label(text: string, color: string = 'primary')}
  <div class="tooltip [--tooltip-color:#191E24]" data-tip={getTooltipText(text)}>
    <span
      class="badge badge-ghost badge-outline badge-sm flex-shrink-0 opacity-70 group-focus-within:opacity-0 {color ===
      'primary'
        ? 'border-primary'
        : 'border-white'} bg-neutral p-2.5 text-transparent shadow-error [text-shadow:_0_1px_0_var(--tw-primary)]"
      style="text-shadow: 0 0 0 {color === 'primary' ? '#F04D7F' : 'white'};"
      >{text}</span>
  </div>
{/snippet}

{#if absolute}
  <div class="flex flex-shrink-0 flex-row gap-2.5 group-focus-within:opacity-0">
    {#if isGenAI}
      {@render label('✨', 'white')}
    {/if}

    {#if locale}
      {@render label(
        locale.replace('zh-hant', 'HK').replace('zh-hans', 'CN').toUpperCase(),
        'primary'
      )}
    {/if}
  </div>
{:else}
  {#if isGenAI}
    {@render label('✨', 'white')}
  {/if}

  {#if locale}
    {@render label(
      locale.replace('zh-hant', 'HK').replace('zh-hans', 'CN').toUpperCase(),
      'primary'
    )}
  {/if}
{/if}
