name: "GIT :: Auto Update Branches"
on:
  push: {}

jobs:
  autoupdate:
    name: "GIT :: Refresh target branch"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'