name: "LINT :: Git Commits"

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: 'GIT :: Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'INSTALL :: Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.15'

      - name: 'INSTALL :: Commitlint'
        run: bun add -d @commitlint/cli @commitlint/config-conventional

      - name: 'LOG :: Versions'
        run: |
          git --version
          node --version
          bun --version
          bunx commitlint --version

      - name: 'ASSERT :: Last commit format'
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: 'ASSERT :: PR commit format'
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose