name: "DEPLOY :: Cloudflare"

on:
  push:
    branches:
      - main
      - preview

jobs:
  deploy-to-prod:
    name: Deploy to Cloudflare [Production]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'GIT :: Checkout'
        uses: actions/checkout@v4

      - name: 'INSTALL :: Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.15'

      - name: 'INSTALL :: Dependencies'
        run: bun install --frozen-lockfile

      - name: 'BUILD :: Application'
        run: bun run build
        env:
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          PRIVATE_AUTH_GOOGLE_ID: ${{ secrets.PRIVATE_AUTH_GOOGLE_ID }}
          PRIVATE_AUTH_GOOGLE_SECRET: ${{ secrets.PRIVATE_AUTH_GOOGLE_SECRET }}
          PRIVATE_AUTH_SECRET: ${{ secrets.PRIVATE_AUTH_SECRET }}
          PRIVATE_AZURE_TRANSLATION_KEY: ${{ secrets.PRIVATE_AZURE_TRANSLATION_KEY }}
          PRIVATE_CLOUDINARY_API_SECRET: ${{ secrets.PRIVATE_CLOUDINARY_API_SECRET }}
          PRIVATE_SUPERADMIN_USERID: ${{ secrets.PRIVATE_SUPERADMIN_USERID }}
          PUBLIC_AZURE_TRANSLATION_REGION: ${{ vars.PUBLIC_AZURE_TRANSLATION_REGION }}
          PUBLIC_GIPHY_KEY: ${{ vars.PUBLIC_GIPHY_KEY }}
          VITE_CLOUDINARY_API_KEY: ${{ vars.VITE_CLOUDINARY_API_KEY }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ vars.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_UPLOAD_PRESET: ${{ vars.VITE_CLOUDINARY_UPLOAD_PRESET }}
          VITE_USER_NODE_ENV: ${{ vars.ENVIRONMENT }}
          VITE_WRANGLER_ENV: cf

      - name: 'DB :: Apply migrations'
        run: bun run db:migration:run:cf:prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: 'DEPLOY :: Cloudflare Worker'
        run: bun run deploy:prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-to-preview:
    name: Deploy to Cloudflare [Preview]
    if: github.ref == 'refs/heads/preview'
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: 'GIT :: Checkout'
        uses: actions/checkout@v4

      - name: 'INSTALL :: Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.15'

      - name: 'INSTALL :: Dependencies'
        run: bun install --frozen-lockfile

      - name: 'BUILD :: Application'
        run: bun run build
        env:
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          PRIVATE_AUTH_GOOGLE_ID: ${{ secrets.PRIVATE_AUTH_GOOGLE_ID }}
          PRIVATE_AUTH_GOOGLE_SECRET: ${{ secrets.PRIVATE_AUTH_GOOGLE_SECRET }}
          PRIVATE_AUTH_SECRET: ${{ secrets.PRIVATE_AUTH_SECRET }}
          PRIVATE_AZURE_TRANSLATION_KEY: ${{ secrets.PRIVATE_AZURE_TRANSLATION_KEY }}
          PRIVATE_CLOUDINARY_API_SECRET: ${{ secrets.PRIVATE_CLOUDINARY_API_SECRET }}
          PRIVATE_SUPERADMIN_USERID: ${{ secrets.PRIVATE_SUPERADMIN_USERID }}
          PUBLIC_AZURE_TRANSLATION_REGION: ${{ vars.PUBLIC_AZURE_TRANSLATION_REGION }}
          PUBLIC_GIPHY_KEY: ${{ vars.PUBLIC_GIPHY_KEY }}
          VITE_CLOUDINARY_API_KEY: ${{ vars.VITE_CLOUDINARY_API_KEY }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ vars.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_UPLOAD_PRESET: ${{ vars.VITE_CLOUDINARY_UPLOAD_PRESET }}
          VITE_USER_NODE_ENV: ${{ vars.ENVIRONMENT }}
          VITE_WRANGLER_ENV: cf

      - name: 'DB :: Apply migrations'
        run: bun run db:migration:run:cf:preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: 'DEPLOY :: Cloudflare Worker'
        run: bun run deploy:preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
