name: "VERSION :: Release"

on:
  push:
    branches:
      - main

env:
  DO_NOT_TRACK: 1

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'GIT :: Checkout Repo'
        uses: actions/checkout@v4

      - name: 'INSTALL :: Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '24.2'

      - name: 'INSTALL :: Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15

      - name: 'CACHE :: Dependencies'
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .svelte-kit
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: 'INSTALL :: Dependencies'
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bun install

      - name: 'RELEASE :: Create Release PR'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run cs:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}